leftnav:
- identifier: 1f7e7a96-ef0d-4ab0-b32e-5f9a5548884c
  name: Main branch page
  url: /pages/page-made-with-main-branch
  weight: 10
- identifier: 2e2a2251-3efe-4956-a9e4-004de7d78924
  name: page two link
  url: /pages/a-new-page-for-a-new-site
  weight: 20
- identifier: 3c2a6275-cfb8-48bf-a08b-61706f77dd8c
  name: Hi Page
  url: /pages/hi
  weight: 30
- identifier: 0dade067-530b-49dc-8d5d-b6d73f60e821
  name: LFF
  url: /pages/link-to-file-in-folder-page
  weight: 40
